<?php
namespace Nakhostin\PerformanceEngine\Optimization;
use Nakhostin\PerformanceEngine\Assets\AssetRegistry;
use Nakhostin\PerformanceEngine\Assets\AssetUsagePlanner;
use Nakhostin\PerformanceEngine\CSS\CriticalCSSGenerator;
use Nakhostin\PerformanceEngine\CSS\CSSManifest;
use Nakhostin\PerformanceEngine\CSS\FontManifest;
use Nakhostin\PerformanceEngine\CSS\FontPreloadPlanner;
use Nakhostin\PerformanceEngine\Infrastructure\Settings;
use Nakhostin\PerformanceEngine\JavaScript\JavaScriptManifest;

final class OptimizationManifestBuilder {
	private $storage; private $critical; private $fonts; private $assets; private $settings;
	public function __construct( OptimizationManifestStorage $storage, CriticalCSSGenerator $critical, FontPreloadPlanner $fonts, AssetUsagePlanner $assets, Settings $settings ) { $this->storage = $storage; $this->critical = $critical; $this->fonts = $fonts; $this->assets = $assets; $this->settings = $settings; }
	public function register(): void { add_action( 'npe/analysis/completed', array( $this, 'build' ), 10, 7 ); }
	public function build( string $url, array $dom, array $components, string $css_source, ?CSSManifest $css, ?JavaScriptManifest $javascript, ?FontManifest $font ): bool { if ( ! $this->settings->get( 'optimization.enabled', false ) || '' === $url || ! $css || ! $javascript ) { return false; } $signature = sanitize_key( (string) ( $dom['dom_signature'] ?? hash( 'sha256', $url ) ) ); $critical = $this->critical->generate( $css_source, $css, $signature, $this->component_ids( $components ) ); $registry = new AssetRegistry(); $js = $javascript->to_array(); foreach ( (array) ( $js['assets'] ?? array() ) as $handle => $asset ) { $registry->register( (string) $handle, 'script', (array) ( $asset['dependencies'] ?? array() ) ); } $safe_mode = (bool) $this->settings->get( 'optimization.safe_mode', true ); $decisions = $this->assets->plan( $registry, array( 'required' => $js['required'] ?? array(), 'explicitly_absent' => $js['unused_candidates'] ?? array() ), $safe_mode ); foreach ( $decisions as $handle => &$decision ) { $decision['type'] = 'script'; } unset( $decision ); $preloads = $font ? $this->fonts->plan( $font, 2 ) : array(); $summary = array( 'css' => array( 'observed' => (int) ( $css->to_array()['selector_count'] ?? 0 ), 'critical_bytes' => strlen( (string) ( $critical->to_array()['css'] ?? '' ) ), 'unchanged' => true ), 'javascript' => array( 'observed' => (int) ( $js['file_count'] ?? 0 ), 'deferred' => count( (array) ( $js['deferred'] ?? array() ) ), 'unloaded' => count( array_filter( $decisions, static function ( array $decision ): bool { return 'unload' === $decision['decision']; } ) ) ), 'fonts' => array( 'preloaded' => count( $preloads ) ) ); return $this->storage->save( new OptimizationManifest( array( 'page_signature' => $signature, 'generated_at' => time(), 'source_url' => esc_url_raw( $url ), 'dom_signature' => (string) ( $dom['dom_signature'] ?? '' ), 'css' => array( 'critical' => $critical->to_array()['css'], 'stylesheets' => array() ), 'javascript' => array( 'manifest' => $js ), 'fonts' => array( 'preloads' => $preloads ), 'assets' => array( 'decisions' => array_values( $decisions ) ), 'components' => $this->component_ids( $components ), 'summary' => $summary ) ) ); }
	private function component_ids( array $components ): array { $ids = array(); foreach ( $components as $component ) { if ( is_object( $component ) && method_exists( $component, 'id' ) ) { $ids[] = $component->id(); } elseif ( is_object( $component ) && method_exists( $component, 'get_id' ) ) { $ids[] = $component->get_id(); } elseif ( is_object( $component ) && method_exists( $component, 'to_array' ) ) { $data = $component->to_array(); $ids[] = (string) ( $data['id'] ?? '' ); } } return array_values( array_filter( array_unique( $ids ) ) ); }
}
