<?php
namespace Nakhostin\PerformanceEngine\Optimization;
use Nakhostin\PerformanceEngine\Assets\AssetRuntimeOptimizer;
use Nakhostin\PerformanceEngine\CSS\CSSRuntimeOptimizer;
use Nakhostin\PerformanceEngine\Infrastructure\Settings;
use Nakhostin\PerformanceEngine\JavaScript\JavaScriptManifest;
use Nakhostin\PerformanceEngine\JavaScript\JavaScriptRuntimeOptimizer;

final class OptimizationCoordinator {
	private $settings; private $storage; private $owners; private $policy; private $css; private $javascript; private $assets; private $context; private $manifest;
	public function __construct( Settings $settings, OptimizationManifestStorage $storage, OptimizationOwnershipResolver $owners, OptimizationPolicy $policy, CSSRuntimeOptimizer $css, JavaScriptRuntimeOptimizer $javascript, AssetRuntimeOptimizer $assets ) { $this->settings = $settings; $this->storage = $storage; $this->owners = $owners; $this->policy = $policy; $this->css = $css; $this->javascript = $javascript; $this->assets = $assets; }
	public function register(): void { add_filter( 'npe/css/optimization_enabled', array( $this, 'allow_css' ), 5 ); add_filter( 'npe/javascript/optimization_enabled', array( $this, 'allow_javascript' ), 5 ); add_filter( 'npe/fonts/optimization_enabled', array( $this, 'allow_fonts' ), 5 ); if ( ! $this->settings->get( 'optimization.enabled', false ) ) { return; } add_action( 'wp_enqueue_scripts', array( $this, 'apply_assets' ), 999 ); add_action( 'wp_head', array( $this, 'render_head' ), 2 ); }
	public function allow_css( $enabled ): bool { return (bool) $enabled && ! in_array( $this->owners->owners( array( 'css' ) )['css'], array( 'external', 'litespeed' ), true ); }
	public function allow_javascript( $enabled ): bool { return (bool) $enabled && ! in_array( $this->owners->owners( array( 'javascript' ) )['javascript'], array( 'external', 'litespeed' ), true ); }
	public function allow_fonts( $enabled ): bool { return (bool) $enabled && ! in_array( $this->owners->owners( array( 'fonts' ) )['fonts'], array( 'external', 'litespeed' ), true ); }
	public function context(): OptimizationContext { if ( $this->context ) { return $this->context; } $type = function_exists( 'is_cart' ) && is_cart() ? 'cart' : ( function_exists( 'is_checkout' ) && is_checkout() ? 'checkout' : ( function_exists( 'is_account_page' ) && is_account_page() ? 'account' : ( function_exists( 'is_product' ) && is_product() ? 'product' : ( function_exists( 'is_shop' ) && is_shop() ? 'shop' : 'page' ) ) ) ); $this->context = new OptimizationContext( array( 'url' => $this->url(), 'page_type' => $type, 'logged_in' => is_user_logged_in(), 'admin' => is_admin(), 'providers' => $this->owners->owners( array( 'css', 'javascript', 'fonts', 'assets' ) ) ) ); return $this->context; }
	public function manifest(): ?OptimizationManifest { if ( null === $this->manifest ) { $this->manifest = $this->storage->for_url( $this->url() ); } return $this->manifest; }
	public function apply_assets(): void { $context = $this->context(); $manifest = $this->manifest(); if ( ! $this->settings->get( 'optimization.enabled', false ) || $context->is_protected() ) { return; } $safe = (bool) $this->settings->get( 'optimization.safe_mode', true ); if ( $this->policy->allows( $context, $manifest, 'css', true )['allowed'] ) { $this->css->apply( $manifest->section( 'css' ), $safe || ! $this->settings->get( 'css.unused_css_enabled', false ) ); } if ( $this->policy->allows( $context, $manifest, 'javascript', (bool) $this->settings->get( 'javascript.defer_enabled', false ) )['allowed'] ) { $js = $manifest->section( 'javascript' ); if ( ! empty( $js['manifest'] ) ) { $this->javascript->apply( new JavaScriptManifest( $js['manifest'] ), $context->to_array(), true, (bool) $this->settings->get( 'assets.unload_enabled', false ) && ! $safe ); } } if ( $this->policy->allows( $context, $manifest, 'assets', (bool) $this->settings->get( 'assets.unload_enabled', false ) )['allowed'] && ! $safe ) { $this->assets->apply( $manifest->section( 'assets' )['decisions'] ?? array() ); } }
	public function render_head(): void { $context = $this->context(); $manifest = $this->manifest(); if ( $context->is_protected() || ! $manifest ) { return; } if ( $this->policy->allows( $context, $manifest, 'css', (bool) $this->settings->get( 'css.critical_css_enabled', false ) )['allowed'] ) { $this->css->inline( (string) ( $manifest->section( 'css' )['critical'] ?? '' ) ); } if ( $this->policy->allows( $context, $manifest, 'fonts', (bool) $this->settings->get( 'fonts.preload_enabled', false ) )['allowed'] ) { foreach ( array_slice( (array) ( $manifest->section( 'fonts' )['preloads'] ?? array() ), 0, 2 ) as $font ) { echo '<link rel="preload" href="' . esc_url( (string) ( $font['url'] ?? '' ) ) . '" as="font" type="' . esc_attr( (string) ( $font['type'] ?? 'font/woff2' ) ) . '" crossorigin>'; } } }
	private function url(): string { $host = isset( $_SERVER['HTTP_HOST'] ) ? preg_replace( '/[^A-Za-z0-9.\-:\[\]]/', '', wp_unslash( $_SERVER['HTTP_HOST'] ) ) : (string) wp_parse_url( home_url( '/' ), PHP_URL_HOST ); $uri = isset( $_SERVER['REQUEST_URI'] ) ? (string) wp_unslash( $_SERVER['REQUEST_URI'] ) : '/'; return ( is_ssl() ? 'https://' : 'http://' ) . $host . '/' . ltrim( strtok( $uri, '?' ) ?: '/', '/' ); }
}
