<?php
namespace Nakhostin\PerformanceEngine\Tests\Unit;
use Nakhostin\PerformanceEngine\Assets\AssetRegistry;
use Nakhostin\PerformanceEngine\Assets\AssetUsagePlanner;
use Nakhostin\PerformanceEngine\CSS\CriticalCSSGenerator;
use Nakhostin\PerformanceEngine\CSS\CSSManifest;
use Nakhostin\PerformanceEngine\CSS\FontManifest;
use Nakhostin\PerformanceEngine\CSS\FontPreloadPlanner;
use Nakhostin\PerformanceEngine\CSS\UnusedCSSPolicy;
use Nakhostin\PerformanceEngine\Optimization\OptimizationContext;
use Nakhostin\PerformanceEngine\Optimization\OptimizationManifest;
use Nakhostin\PerformanceEngine\Optimization\OptimizationOwnershipResolver;
use Nakhostin\PerformanceEngine\Optimization\OptimizationPolicy;
use Nakhostin\PerformanceEngine\Optimization\OptimizationManifestStorage;
use Nakhostin\PerformanceEngine\Optimization\OptimizationProviderInterface;
use PHPUnit\Framework\TestCase;

final class OptimizationEngineTest extends TestCase {
	public function test_dynamic_css_selectors_are_always_preserved(): void { $policy = new UnusedCSSPolicy(); foreach ( array( 'a:hover', '.menu.open', '.is-loading', '.has-error', '.woocommerce-cart', '.elementor-widget', '.wd-dropdown', 'input:focus-visible', '.icon::before' ) as $selector ) { self::assertSame( UnusedCSSPolicy::DYNAMIC_REQUIRED, $policy->classify( $selector, array() ), $selector ); } }
	public function test_critical_css_manifest_contains_only_observed_rules(): void { $usage = new CSSManifest( array( 'used' => array( '.hero' ), 'preserved' => array( '.modal.open' ) ) ); $manifest = ( new CriticalCSSGenerator() )->generate( '.hero{color:red}.missing{color:blue}.modal.open{display:block}', $usage, 'page-one' ); self::assertTrue( $manifest->is_valid() ); self::assertStringContainsString( '.hero{color:red}', $manifest->to_array()['css'] ); self::assertStringNotContainsString( '.missing', $manifest->to_array()['css'] ); }
	public function test_unknown_assets_fall_back_to_keep_and_safe_mode_never_unloads(): void { $registry = new AssetRegistry(); $registry->register( 'unknown-widget', 'script' ); $decisions = ( new AssetUsagePlanner() )->plan( $registry, array( 'explicitly_absent' => array( 'unknown-widget' ) ), true ); self::assertSame( 'keep', $decisions['unknown-widget']['decision'] ); }
	public function test_explicit_high_confidence_asset_can_unload_outside_safe_mode(): void { $registry = new AssetRegistry(); $registry->register( 'absent-widget', 'script' ); $decisions = ( new AssetUsagePlanner() )->plan( $registry, array( 'capture_complete' => true, 'explicitly_absent' => array( 'absent-widget' ) ), false ); self::assertSame( 'unload', $decisions['absent-widget']['decision'] ); self::assertSame( 100, $decisions['absent-widget']['confidence'] ); }
	public function test_font_preload_prefers_woff2_and_caps_at_two(): void { $manifest = new FontManifest( array( 'families' => array( array( 'faces' => array( array( 'required' => true, 'sources' => array( array( 'url' => 'https://example.test/a.woff' ), array( 'url' => 'https://example.test/a.woff2' ) ) ), array( 'required' => true, 'sources' => array( array( 'url' => 'https://example.test/b.woff2' ), array( 'url' => 'https://example.test/c.woff2' ) ) ) ) ) ) ) ); $plan = ( new FontPreloadPlanner() )->plan( $manifest ); self::assertCount( 2, $plan ); self::assertStringEndsWith( '.woff2', $plan[0]['url'] ); self::assertStringEndsWith( '.woff2', $plan[1]['url'] ); }
	public function test_stale_and_protected_contexts_keep_original_assets(): void { $provider = new class implements OptimizationProviderInterface { public function id(): string { return 'npe'; } public function owns( string $feature ): bool { return true; } public function priority( string $feature ): int { return 1; } }; $owners = ( new OptimizationOwnershipResolver( array( $provider ) ) )->owners( array( 'css' ) ); $policy = new OptimizationPolicy(); $stale = new OptimizationManifest( array( 'page_signature' => 'x', 'generated_at' => 1, 'source_url' => 'https://example.test/' ) ); self::assertSame( 'manifest-stale', $policy->allows( new OptimizationContext( array( 'providers' => $owners ) ), $stale, 'css', true )['reason'] ); $fresh = new OptimizationManifest( array( 'page_signature' => 'x', 'generated_at' => time(), 'source_url' => 'https://example.test/' ) ); self::assertSame( 'protected-context', $policy->allows( new OptimizationContext( array( 'providers' => $owners, 'page_type' => 'checkout' ) ), $fresh, 'css', true )['reason'] ); }
	public function test_missing_manifest_fails_open(): void { $provider = new class implements OptimizationProviderInterface { public function id(): string { return 'npe'; } public function owns( string $feature ): bool { return true; } public function priority( string $feature ): int { return 1; } }; $owners = ( new OptimizationOwnershipResolver( array( $provider ) ) )->owners( array( 'assets' ) ); self::assertSame( 'manifest-missing', ( new OptimizationPolicy() )->allows( new OptimizationContext( array( 'providers' => $owners ) ), null, 'assets', true )['reason'] ); }
	public function test_feature_specific_provider_priority_avoids_duplicate_work(): void { $npe = new class implements OptimizationProviderInterface { public function id(): string { return 'npe'; } public function owns( string $feature ): bool { return true; } public function priority( string $feature ): int { return 10; } }; $external = new class implements OptimizationProviderInterface { public function id(): string { return 'external'; } public function owns( string $feature ): bool { return 'css' === $feature; } public function priority( string $feature ): int { return 100; } }; $owners = ( new OptimizationOwnershipResolver( array( $npe, $external ) ) )->owners( array( 'css', 'javascript', 'fonts' ) ); self::assertSame( array( 'css' => 'external', 'javascript' => 'npe', 'fonts' => 'npe' ), $owners ); }
	public function test_incompatible_manifest_is_rejected_by_storage(): void { $GLOBALS['npe_test_options'][ OptimizationManifestStorage::OPTION ] = array( hash( 'sha256', 'https://example.test/legacy/' ) => array( 'manifest_version' => 2, 'page_signature' => 'legacy', 'generated_at' => time(), 'source_url' => 'https://example.test/legacy/' ) ); self::assertNull( ( new OptimizationManifestStorage() )->for_url( 'https://example.test/legacy/' ) ); }
	public function test_malformed_incomplete_manifest_cannot_authorize_unload(): void { $url = 'https://example.test/malformed/'; $GLOBALS['npe_test_options'][ OptimizationManifestStorage::OPTION ] = array( hash( 'sha256', $url ) => array( 'manifest_version' => 3, 'page_signature' => 'bad', 'generated_at' => time(), 'source_url' => $url, 'capture' => array( 'status' => 'incomplete', 'complete' => false ), 'assets' => array( 'decisions' => array( array( 'handle' => 'unsafe', 'type' => 'script', 'decision' => 'unload', 'reason' => 'bad', 'confidence' => 100 ) ) ) ) ); self::assertNull( ( new OptimizationManifestStorage() )->for_url( $url ) ); }
}
